---
title: "Final"
author: "Adil Hayat"
date: "8 March 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(0)
```

# all the libraries and source code
```{r}
library(fANCOVA)
library(tidyverse)
library(car)
library(mgcv)
library(tree)
library(randomForest)
library(quantmod)
library(bestglm)
source("http://www.stat.cmu.edu/~cschafer/MSCF/CVforppr.R")
source("http://www.stat.cmu.edu/~cschafer/MSCF/CVfornnet.R")
source("http://www.stat.cmu.edu/~cschafer/MSCF/cv.tree.full.txt")
```

# Parameters
```{r}
ppdata = read.table("http://www.stat.cmu.edu/~cschafer/MSCF/PowerPlant.txt", header=T)
```


# Question 1
```{r}
# histgrams
par(mfrow= c(2,2))
hist(ppdata$AT)
hist(ppdata$V)
hist(ppdata$AP)
hist(ppdata$RH)

par(mfrow= c(2,2))
hist(log(ppdata$AT))
hist(log(ppdata$V))
hist(log(ppdata$AP))
hist(log(ppdata$RH))
par(mfrow= c(1,2))
hist(ppdata$V)
hist(log(ppdata$V))

# linear regression
linmod <- lm(PE~AT+V+AP+RH, data = ppdata)
summary(linmod)


# qq plot
dat= data.frame(linmod$fitted.values,linmod$residuals)
names(dat) <- c("Fitted_Values","Residuals")
ggplot(dat, aes(x=Fitted_Values, y=Residuals)) +
  geom_point(shape=1)
qqnorm(dat$Residuals);qqline(dat$Residuals, col=2)

# Cook's distance
cookd = as.numeric(cooks.distance(linmod))
numcoeff <- length(linmod$coefficients)
sort(pf(cookd, numcoeff, nrow(ppdata) - numcoeff),decreasing=TRUE)[1:5]
plot(cookd)
which.max(cookd)
pf(cookd[3118], numcoeff, nrow(ppdata) - numcoeff)


# 5
Xyframe = ppdata
bestmod = bestglm(Xyframe, IC="AIC")
summary(bestmod$BestModel)


intrmod <- lm(PE~AT+V+AP+RH+AT:V, data = ppdata)
summary(intrmod)
AIC(intrmod)
AIC(linmod)
AIC(bestmod$BestModel)
```
# Question 7
```{r}
gammodel = gam( PE ~ s(AT)+ s(V) + s(AP) + s(RH) , data=ppdata, method = "GCV.Cp")
summary(gammodel)
plot(gammodel, pages=1,scale=0,scheme=1)
```



# Question 8
```{r}
pred = predict(gammodel)
plot(pred, ppdata$PE, pch=16,cex=0.7,xlab="Predicted Value",
   ylab="Actual Response", cex.axis=1.3,cex.lab=1.3, main= "Actual vs Pred.")
abline(0,1,lwd=2,col=2)
```

# Question 9
```{r}
pprdata = ppdata[1:2000,]
PPRmod = ppr(PE~AT+V+AP+RH, nterms = 1, data=pprdata, sm.method="gcvspline")
summary(PPRmod)

```
# Question 10
```{r}
ppdata$usagelevel = as.numeric(ppdata$PE > 450)

fulltree = tree(factor(usagelevel)~ AT+V+AP+RH, data =ppdata , mindev=0, minsize=2)
cvout = cv.tree.full(fulltree)

optaplha = cvout$k[which.min(cvout$dev)]

opttree = prune.tree(fulltree, k=optaplha)
plot(opttree)
text(opttree, cex=0.75)
summary(opttree)

plot(cvout)
abline(v = 20)
```

# Question 11
```{r}
cvout$size[which.min(cvout$dev)]
```

# Question 13
```{r}
plot(ppdata$AT, ppdata$PE,pch=".")

lofit = loess.as(ppdata$AT, ppdata$PE, criterion = "gcv")
lofit$enp

plot(lofit$fitted,lofit$residuals)

```


